FROM debian:bullseye

#ADD	sources.list	/etc/apt/sources.list

RUN	apt-get update \
	&& apt-get install -y apt-utils \ 
	&& apt-get upgrade -y \
	&& apt-get install -y ##LINUX_IMAGE### ###LINUX_HEADERS### linux-source\
	&& apt-get install -y build-essential libxtables-dev libip6tc-dev libip4tc-dev iptables conntrack libnetfilter-conntrack-dev libxtables-dev \
	&& apt-get install -y autoconf libtool git libpcap-dev libjson-c-dev \
	&& apt-get clean -y && apt-get autoclean -y && apt-get autoremove -y

ADD	clean.sh /clean.sh

RUN	chmod +x /clean.sh \
	&& /bin/bash clean.sh

RUN mkdir /build
VOLUME /build
CMD ["/build/build.sh"]

